[project]
name = "hybgensea"
version = "0.1.1"
authors = [{name = "Changhyun Kwon"}, {name = "Mauricio Souza de Alencar", email="ma___@dtu.dk" }]
description = "Wrapper for the Hybrid Genetic Search algorithm for Capacitated Vehicle Routing Problems (HGS-CVRP)"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python=">=3.10"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
"Issue Tracker" = "https://github.com/mdealencar/HybGenSea/issues"
"Source" = "https://github.com/mdealencar/HybGenSea"

[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.build-type = "Release"
